### ISSUE TITLE
Upload and re-upload fails

### ISSUE THREAD

**Issue by CodingLama** [exander77/vicuna#11]
Priority 2
Linux Ubuntu, Java 15.0.2., VU 1.3.2a

One of 11 files hasn't been uploaded and it could not be reuploaded. The error message states:

```
Jan 23, 2022 12:03:05 PM cuploader.frames.FUpload$3 run
SEVERE: error: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1428"><error code="badupload" info="The file for &quot;chunk&quot; was only partially uploaded." xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&amp;gt; for notice of API deprecations and breaking changes.</error></api>
java.lang.UnknownError: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1428"><error code="badupload" info="The file for &quot;chunk&quot; was only partially uploaded." xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&amp;gt; for notice of API deprecations and breaking changes.</error></api>
	at org.wikipedia.Wiki.detectUncheckedErrors(Wiki.java:8383)
	at org.wikipedia.Wiki.checkErrorsAndUpdateStatus(Wiki.java:8459)
	at org.wikipedia.Wiki.upload(Wiki.java:4393)
	at cuploader.frames.FUpload$3.run(FUpload.java:377)
	at java.base/java.lang.Thread.run(Thread.java:832)

```
So if I understand it well, some portions (chunks) of the file haven't been uploaded. Does VU try to reupload these chunks if this occurs or there is just one try? It's weird that it fails again and again with the same file. Could there be something like cache, which blocks the same file to be reuploaded due to the first "bad" experience? I remember that in the past it was possible to upload even some parts of a file, but this was fixed, so maybe the way would be to register to the mentioned mailing list and asked there.

**Comment by CodingLama** [comment]
Note these files are not in [special:uploadStash](https://commons.wikimedia.org/wiki/Special:UploadStash).

**Comment by CodingLama** [comment]
So it happened again and I have tried multiple choices while renaming that file in the folder (outside VU) worked. See the operation log:

1) File _IMG_5602.JPG_ named in _VU Sluštice (33)_

Cannot upload nor re-upload, the error message is:

```
Jan 26, 2022 6:32:36 PM cuploader.frames.FUpload$3 run
SEVERE: error: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1423"><error code="badupload" info="The file for &quot;chunk&quot; was only partially uploaded." xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&amp;gt; for notice of API deprecations and breaking changes.</error></api>
java.lang.UnknownError: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1423"><error code="badupload" info="The file for &quot;chunk&quot; was only partially uploaded." xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&amp;gt; for notice of API deprecations and breaking changes.</error></api>
	at org.wikipedia.Wiki.detectUncheckedErrors(Wiki.java:8383)
	at org.wikipedia.Wiki.checkErrorsAndUpdateStatus(Wiki.java:8459)
	at org.wikipedia.Wiki.upload(Wiki.java:4393)
	at cuploader.frames.FUpload$3.run(FUpload.java:377)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

2) If I clear the session load the file again and try to upload it, it fails (and also reupload fails) with the following error message:

```
Jan 26, 2022 6:36:03 PM cuploader.frames.FUpload$3 run
SEVERE: error: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1314"><error code="badupload" info="The file for &quot;chunk&quot; was only partially uploaded." xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&amp;gt; for notice of API deprecations and breaking changes.</error></api>
java.lang.UnknownError: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1314"><error code="badupload" info="The file for &quot;chunk&quot; was only partially uploaded." xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&amp;gt; for notice of API deprecations and breaking changes.</error></api>
	at org.wikipedia.Wiki.detectUncheckedErrors(Wiki.java:8383)
	at org.wikipedia.Wiki.checkErrorsAndUpdateStatus(Wiki.java:8459)
	at org.wikipedia.Wiki.upload(Wiki.java:4393)
	at cuploader.frames.FUpload$3.run(FUpload.java:377)
	at java.base/java.lang.Thread.run(Thread.java:832)
```


3) Then I clear the session again and rename the file in the folder from _IMG_5602.JPG_ to _IMG_5602a.JPG_. I have loaded it again to VU, describe and it was successfully uploaded. See it on [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Slu%C5%A1tice_(33).jpg).

**Comment by exander77** [comment]
Mělo by být opraveno v 1.3.3a, případně znovu otevřít.
